import bcrypt from 'bcrypt';
import jwt from 'jsonwebtoken';
import { userRepository, UserEntity } from '../db/UserRepository.js';
import { Sanitizer } from '../utils/sanitizer.js';
import { JWT_SECRET } from '../secrets.js';

const SALT_ROUNDS = 12;

export enum AuthError {
    FAILED = 'AUTH_FAILED',
    EMAIL_EXISTS = 'EMAIL_EXISTS',
    REG_FAILED = 'REGISTRATION_FAILED',
    NOT_FOUND = 'USER_NOT_FOUND'
}

export interface AuthResponse {
    user: UserEntity;
    token: string;
}

export class AuthService {
    private secret = JWT_SECRET || (process.env.NODE_ENV === 'production' ? '' : 'dev_only_soundvzn_secret_change_me');

    constructor() {
        if (!this.secret) {
            throw new Error('JWT_SECRET is required in production');
        }
    }

    public async login(email: string, password_plain: string, ip: string): Promise<AuthResponse> {
        const user = userRepository.findByEmail(email.trim().toLowerCase());
        if (!user) {
            throw new Error(AuthError.FAILED);
        }

        const isMatch = await bcrypt.compare(password_plain, user.password_hash);
        if (!isMatch) {
            // Log failed attempt for security auditing
            this.audit(user.id, 'LOGIN_FAILED', ip);
            throw new Error('AUTH_FAILED');
        }

        if (!user.verified) {
            this.audit(user.id, 'LOGIN_UNVERIFIED', ip);
            throw new Error('ACCOUNT_NOT_VERIFIED');
        }

        const token = this.generateToken(user);
        this.audit(user.id, 'LOGIN_SUCCESS', ip);
        
        return { user, token };
    }

    public async register(data: Partial<UserEntity>, ip: string) {
        if (userRepository.findByEmail(data.email!)) {
            throw new Error('EMAIL_EXISTS');
        }

        const password_hash = await bcrypt.hash(data.password_hash!, SALT_ROUNDS);
        const newUser: UserEntity = {
            id: crypto.randomUUID(),
            email: data.email!.toLowerCase().trim(),
            password_hash,
            name: Sanitizer.clean(data.name!),
            username: Sanitizer.cleanUsername(data.username || ''),
            tier: 'pro',
            verified: 0,
            created_at: Date.now()
        };

        const success = userRepository.create(newUser);
        if (success) {
            this.audit(newUser.id, 'REGISTER_SUCCESS', ip);
            // Fetch back to get svzn_id generated by DB
            const fullUser = userRepository.findById(newUser.id);
            return fullUser || newUser;
        }
        throw new Error('REGISTRATION_FAILED');
    }

    private generateToken(user: UserEntity): string {
        return jwt.sign(
            {
                id: user.id,
                svzn_id: user.svzn_id,
                email: user.email,
                tier: user.tier || 'standard',
                username: user.username,
            },
            this.secret,
            { expiresIn: '7d' }
        );
    }

    private audit(userId: string, action: string, ip: string) {
        // Implementation for audit logging in DB
        console.log(`[Audit] ${action} for ${userId} from ${ip}`);
    }
}

export const authService = new AuthService();
