export default {};
export const existsSync = () => false;
export const readFileSync = () => '';
export const writeFile = () => {};
export const join = (...args: string[]) => args.join('/');
export const resolve = (...args: string[]) => args.join('/');
export const dirname = (p: string) => p;
export const homedir = () => '/';
export const platform = () => 'web';
export const arch = () => 'x64';
export const release = () => '1.0.0';
export const tmpdir = () => '/tmp';
export const exec = () => {};
export const spawn = () => {};
